name: Deploy GAS as Web App

on:
  push:
    branches:
      - main

# .github/workflows/deploy-gas-webapp.yml （抜粋）
jobs:
  deploy-gas-webapp:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install clasp (latest)
        run: npm install --global @google/clasp@latest

      - name: Configure ~/.clasprc.json for clasp authentication
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json

      - name: Push & Deploy as Web App
        id: deploy
        run: |
          set -eux

          # 1) ローカルのファイルを Apps Script に強制アップロード
          clasp push --force

          # 2) 新しいバージョンを JSON 形式で作成し、versionNumber を抜き出す
          NEW_VER=$(
            clasp version "auto-$(date +%Y%m%d%H%M%S)" --json \
              | jq -r '.versionNumber'
          )
          # もし NEW_VER が空だったらエラー扱い
          if [ -z "$NEW_VER" ]; then
            echo "Failed to retrieve version number" >&2
            exit 1
          fi
          echo "→ 新しいバージョン番号: $NEW_VER"

          # 3) 既存の DEPLOYMENT_ID を使って上書きデプロイ
          #    (--webapp や --type webapp は不要。初回作成時のみ --type webapp を実行済みの前提)
          clasp deploy \
            --deploymentId "${DEPLOYMENT_ID}" \
            --versionNumber "${NEW_VER}" \
            --description "auto-deploy from GitHub Actions"

          # 4) 公開 URL を組み立て (?page=login を末尾に追加)
          FINAL_URL="https://script.google.com/macros/s/${DEPLOYMENT_ID}/exec?page=login"
          echo "✅ Web アプリ最新版の URL: ${FINAL_URL}"

          # GitHub Actions の出力値にもセット
          echo "webapp_url=${FINAL_URL}" >> "$GITHUB_OUTPUT"

      - name: Show output webapp_url
        run: |
          echo "==== 出力された webapp_url ===="
          echo "${{ steps.deploy.outputs.webapp_url }}"
