# .github/workflows/deploy-gas-app.yml
name: deploy-gas-app

concurrency:
  group: deploy-gas-app
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/**'

permissions:
  contents: write

env:
  NODE_VERSION: 20
  CLASP_VERSION: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 1

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - run: npm ci

    # ── version 取得
    - id: pkg_ver
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

    # ── build version を埋め込み
    - run: sed -i "s/__BUILD_VERSION__/v${{ steps.pkg_ver.outputs.VERSION }}/" src/Code.gs

    # ── Unit tests
    - run: npm test

    # ── clasp & jq
    - run: |
        npm i -g @google/clasp@${{ env.CLASP_VERSION }}
        sudo apt-get update -y && sudo apt-get install -y jq

    # ── clasp auth
    - run: |
        mkdir -p ~/.config
        echo "${CLASPRC_JSON}" > ~/.clasprc.json

    # ── push & create version
    - run: |
        set -eux
        clasp push --force
        clasp version "v${{ steps.pkg_ver.outputs.VERSION }}"

    # ── update Web-App deployment（既存 ID がある場合）
    - if: env.DEPLOYMENT_ID != ''
      run: |
        set -eux
        VNUM=$(clasp versions | awk '/^[0-9]+/{print $1}' | sort -nr | head -1)
        clasp update-deployment "$DEPLOYMENT_ID" \
          --versionNumber "$VNUM" \
          --description "v${{ steps.pkg_ver.outputs.VERSION }} (auto)"

    # ── commit build artefacts & bump patch
    - if: success()
      run: |
        set -eux
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add -A   # .claspignore も含めて変更すべて
        git commit -m "build: embed v${{ steps.pkg_ver.outputs.VERSION }} [skip ci]" --no-verify

        npm version patch -m "chore: bump to %s [skip ci]" --no-verify
        git pull --rebase --autostash origin main
        git push --follow-tags --force-with-lease
