name: Deploy GAS Project

on:
  push:
    branches:
      - main

jobs:
  deploy-gas:
    name: Deploy GAS via clasp
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    env:
      # リポジトリのシークレットとして登録済み
      # - secrets.GOOGLE_CREDENTIALS : サービスアカウント JSON (auth ステップで利用)
      # - secrets.SCRIPT_ID          : デプロイ対象の Apps Script プロジェクトの Script ID
      GCP_PROJECT: gas-deploy-project
      SERVICE_ACCOUNT: gas-deploy-bot@gas-deploy-project.iam.gserviceaccount.com
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

    steps:
      # 1) ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Node.js をセットアップ（clasp は Node.js 上のツールなので必要）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Google への認証
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ steps.auth.outputs.project_id }}

      # 認証情報から環境変数をエクスポート
      - name: Export env vars
        run: |
          echo "GCP_PROJECT=${{ steps.auth.outputs.project_id }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=$(jq -r '.client_email' \"$GOOGLE_APPLICATION_CREDENTIALS\")" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        id: set-env

      # 4) clasp をインストール（最新の安定版を指定）
      - name: Install clasp (stable)
        run: npm install --global @google/clasp@latest

      # 5) .clasp.json を書き込み（SCRIPT_ID を設定）
      - name: Write .clasp.json
        run: |
          echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json

      # 6) clasp で Apps Script にデプロイ
      - name: Push to Apps Script
        run: |
          echo "=== Deploying to Apps Script via clasp ==="
          # プッシュ実行（ADC を利用）
          clasp push --force --adc
        env:
          SCRIPT_ID: ${{ env.SCRIPT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
