name: Deploy GAS

'on':
  push:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js (>=20.x)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install clasp (v3)
        run: npm install --global @google/clasp@3.0.6-alpha

      - name: Restore GCP service-account key
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" | base64 -d > "$HOME/gcp-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-sa.json" >> $GITHUB_ENV

      - name: Authenticate with clasp
        run: clasp login --creds "$HOME/gcp-sa.json"

      - name: Write .clasp.json
        env:
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
        run: |
          echo "{\"scriptId\":\"$SCRIPT_ID\"}" > .clasp.json

      - name: Push to Google Apps Script
        run: clasp push --force --adc
