# .github/workflows/deploy-gas-app.yml
name: deploy-gas-app
concurrency:
  group: deploy-gas-app
  cancel-in-progress: false
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/**'
permissions:
  contents: write
env:
  NODE_VERSION: 20
  CLASP_VERSION: latest
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 1
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - run: npm ci
    - id: pkg_ver
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
    - run: sed -i "s/__BUILD_VERSION__/v${{ steps.pkg_ver.outputs.VERSION }}/" src/Code.gs
    - run: npm test
    # ------------------------------------------------------------------ #
    # ここから GAS 用セットアップ
    # ------------------------------------------------------------------ #
    - run: |
        npm i -g @google/clasp@${{ env.CLASP_VERSION }}
        sudo apt-get update -y && sudo apt-get install -y jq
    - run: |
        mkdir -p ~/.config
        echo "${CLASPRC_JSON}" > ~/.clasprc.json
    - name: Clean up GAS project files
      run: |
        set -eux
        
        # まず全ファイルリストを取得してデバッグ
        echo "=== Current files in GAS project ==="
        clasp files:list || echo "Failed to list files"
        
        # JSON形式でファイルリストを取得
        echo "=== Getting files in JSON format ==="
        FILES_JSON=$(clasp files:list --json 2>&1) || FILES_JSON="[]"
        echo "Raw files JSON output: $FILES_JSON"
        
        # JSONが有効かチェック
        if echo "$FILES_JSON" | jq . >/dev/null 2>&1; then
          echo "Valid JSON received"
          
          # escapeHtml関連のファイルIDを取得・削除
          echo "$FILES_JSON" | jq -r '.[] | select(.name | test("escapeHtml|shared/escapeHtml")) | "\(.name):\(.id)"' | \
          while IFS=: read -r NAME ID; do
            if [ -n "$ID" ] && [ "$ID" != "null" ]; then
              echo "Found file to delete: $NAME (ID: $ID)"
              echo y | clasp files:delete "$ID" || echo "Failed to delete $ID, continuing..."
            fi
          done
        else
          echo "Invalid JSON or clasp files:list failed"
          echo "Attempting alternative cleanup method..."
          
          # 代替方法：通常のリストから解析
          clasp files:list 2>/dev/null | grep -E "(escapeHtml|shared/escapeHtml)" | \
          while read -r line; do
            echo "Found potential file to clean: $line"
            # この方法では直接削除は困難なので、警告のみ
          done || echo "No escapeHtml files found via alternative method"
        fi
        
        # 少し待機
        sleep 3
        echo "=== Files after cleanup ==="
        clasp files:list || echo "Failed to list files after cleanup"
    
    # ------------------------------------------------------------------ #
    # push & version （強制的なクリーンアップ付き）
    # ------------------------------------------------------------------ #
    - name: Push to GAS & create new version
      run: |
        set -eux
        
        # 方法1: .claspignore で除外する
        echo "shared/escapeHtml*" >> .claspignore
        echo "escapeHtml*" >> .claspignore
        
        # 方法2: ローカルの競合ファイルを削除
        find . -name "*escapeHtml*" -type f -delete || true
        rm -rf shared/escapeHtml* || true
        
        # 方法3: clasp pull で最新状態を取得してから push
        echo "=== Attempting clasp pull to sync ==="
        clasp pull --force || echo "clasp pull failed, continuing..."
        
        # 再度ローカルクリーンアップ
        find . -name "*escapeHtml*" -type f -delete || true
        rm -rf shared/escapeHtml* || true
        
        # clasp push をリトライ機能付きで実行
        MAX_RETRIES=3
        RETRY_COUNT=0
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if clasp push --force; then
            echo "clasp push succeeded"
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "clasp push failed (attempt $RETRY_COUNT/$MAX_RETRIES)"
            
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Trying more aggressive cleanup..."
              
              # より積極的なクリーンアップ
              clasp files:list 2>/dev/null | grep -i escape | head -10 || echo "No escape files found"
              
              # .clasp.json のプロジェクトIDを確認
              echo "Project config:"
              cat .clasp.json || echo "No .clasp.json found"
              
              # 30秒待機（GAS側の同期を待つ）
              echo "Waiting 30 seconds for GAS sync..."
              sleep 30
            else
              echo "Max retries reached. Manual intervention may be required."
              echo "Please manually delete the 'shared/escapeHtml' file from the GAS project."
              exit 1
            fi
          fi
        done
        
        clasp version "v${{ steps.pkg_ver.outputs.VERSION }}"
    - if: env.DEPLOYMENT_ID != ''
      run: |
        set -eux
        VNUM=$(clasp versions | awk '/^[0-9]+/{print $1}' | sort -nr | head -1)
        clasp update-deployment "$DEPLOYMENT_ID" \
          --versionNumber "$VNUM" \
          --description "v${{ steps.pkg_ver.outputs.VERSION }} (auto)"
    # ------------------------------------------------------------------ #
    # GitHub へ通常 push
    # ------------------------------------------------------------------ #
    - if: success()
      run: |
        set -eux
        git config user.name  "github-actions"
        git config user.email "github-actions@github.com"
        git add -A
        git diff --cached --quiet || \
          git commit -m "build: embed v${{ steps.pkg_ver.outputs.VERSION }} [skip ci]" --no-verify
        npm version patch -m "chore: bump to %s [skip ci]" --no-verify
        git pull --rebase --autostash origin main
        git push --follow-tags
