name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

env:
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
  # ここを GCP_CREDENTIALS ではなく GOOGLE_CREDENTIALS に合わせる
  GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy:
    name: Deploy GAS via clasp
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install clasp v3
        run: |
          npm install --global @google/clasp@3.0.6-alpha

      - name: Decode service account key
        run: |
          # Secrets.GOOGLE_CREDENTIALS の値（Base64文字列）を復元してファイルに書き出し
          echo "${GCP_CREDENTIALS}" | base64 -d > "${HOME}/gcp-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-sa.json" >> $GITHUB_ENV

      - name: Generate .clasp.json
        run: |
          mkdir -p ~/.clasprc
          # Secrets.SCRIPT_ID を使って .clasp.json を生成
          echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json

      - name: Push to Apps Script (ADC)
        run: |
          clasp push --force --adc
