# .github/workflows/deploy-gas-webapp.yml
name: deploy-gas-webapp

# ── 同じブランチでは 1 本ずつ直列実行
concurrency:
  group: deploy-gas-webapp

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
    #──────────────────────────────
    # 1. Checkout
    #──────────────────────────────
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 1

    #──────────────────────────────
    # 2. Node + npm cache
    #──────────────────────────────
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # 3. Install deps
    - run: npm ci

    # 4. Get current version
    - id: ver
      run: |
        echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT

    # 5. Inject version into Code.gs
    - run: sed -i "s/__BUILD_VERSION__/v${{ steps.ver.outputs.VERSION }}/" src/Code.gs

    # 6. Tests
    - run: npm test

    # 7. Tools
    - run: |
        npm i -g @google/clasp@latest
        sudo apt-get update -y && sudo apt-get install -y jq

    # 8. clasp auth
    - run: |
        mkdir -p ~/.config
        echo "${CLASPRC_JSON}" > ~/.clasprc.json

    # 9. push → create new version
    - run: |
        set -eux
        clasp push --force
        clasp version "v${{ steps.ver.outputs.VERSION }}"

    # 10. Update deployment  (cut コマンドで安全に取得)
    - run: |
        set -eux
        VNUM=$(clasp versions | head -n1 | cut -d' ' -f1)
        [[ "$VNUM" =~ ^[0-9]+$ ]] || { echo "Bad version: $VNUM"; exit 1; }
        clasp update-deployment "$DEPLOYMENT_ID" \
          --versionNumber "$VNUM" \
          --description "v${{ steps.ver.outputs.VERSION }} (auto-deploy)"

    # 11. Bump patch & push (rebase で stale 回避)
    - if: ${{ success() }}
      run: |
        set -eux
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm version patch -m "chore: bump to %s [skip ci]"
        # リモートを取り込んでから push
        git fetch origin main
        git rebase origin/main
        git push --follow-tags --force-with-lease
