name: Deploy GAS
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js (>=20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install clasp (latest stable)
        run: npm install --global @google/clasp@latest
        
      - name: Verify clasp installation
        run: clasp --version
        
      - name: Restore GCP service-account key
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > "$HOME/gcp-sa.json"
          chmod 600 "$HOME/gcp-sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-sa.json" >> $GITHUB_ENV
          
      - name: Authenticate with clasp
        run: clasp login --creds "$HOME/gcp-sa.json"
        
      - name: Write .clasp.json
        run: |
          echo "{\"scriptId\":\"$SCRIPT_ID\"}" > .clasp.json
          
      - name: Validate project structure
        run: |
          if [ ! -f "appsscript.json" ]; then
            echo "Error: appsscript.json not found"
            exit 1
          fi
          echo "Project structure validated"
          
      - name: Push to Google Apps Script
        run: clasp push --force
        
      - name: Clean up credentials
        if: always()
        run: |
          rm -f "$HOME/gcp-sa.json"
          rm -f .clasp.json
