name: deploy-gas-webapp
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # clasp 認証 JSON を GitHub Secrets に設定しておく
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      # 手動初回デプロイで取得した Web アプリの DEPLOYMENT_ID
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install --global @google/clasp@latest

      - name: Configure clasp auth
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json

      - name: Push & Deploy Web App
        run: |
          set -eux

          # 1) コードを強制アップロード
          clasp push --force

          # 2) 新しいバージョンを作成して番号を取得
          NEW_VER=$(clasp version "auto-$(date +%Y%m%d%H%M%S)" \
            | grep -oE "[0-9]+" | head -n1)
          [ -n "$NEW_VER" ] || (echo "version generation failed" >&2; exit 1)

          # 3) 既存の Web アプリに上書きデプロイ
          clasp deploy \
            --deploymentId "${DEPLOYMENT_ID}" \
            --versionNumber "${NEW_VER}" \
            --description "auto-deploy from GitHub Actions" \
            --type webapp
