name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Node.js（v20）をセットアップして Clasp v3 を使えるようにする
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3) Clasp v3 をインストール
      - name: Install clasp v3
        run: npm install -g @google/clasp@3

      # 4) サービスアカウントJSONを復元し、環境変数で ADC にセット
      - name: Authenticate via ADC
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" | base64 -d > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/credentials.json"
          # .clasp.json がすでにリポジトリにある場合は不要。ただし初回は作成しておく。
          echo "{\"scriptId\":\"${{ secrets.SCRIPT_ID }}\"}" > .clasp.json
          # Clasp v3 で ADC 認証を使ってプッシュ
          clasp push --force --adc
