name: Deploy GAS Project

on:
  push:
    branches:
      - main

jobs:
  deploy-gas:
    name: Deploy GAS via clasp
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    env:
      # GitHub リポジトリのシークレットとして登録済みの変数
      # - secrets.GOOGLE_CREDENTIALS : サービスアカウント JSON (auth ステップで使用)
      # - secrets.SCRIPT_ID          : デプロイ対象の Apps Script プロジェクトの Script ID
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

    steps:
      # 1) ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      # 2) Node.js をセットアップ（clasp は Node.js 上のツールなので必要）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        # ※ 以降のステップで env.SCRIPT_ID はそのまま参照できます

      # 3) Google への認証
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # 認証情報からプロジェクトIDとサービスアカウントを環境変数に設定
      - name: Export env vars
        run: |
          echo "GCP_PROJECT=${{ steps.auth.outputs.project_id }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=$(jq -r '.client_email' \"$GOOGLE_APPLICATION_CREDENTIALS\")" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        id: set-env

      - name: Check Auth / Permissions (Debug)
        run: |
          chmod +x .github/scripts/check_auth.sh
          .github/scripts/check_auth.sh

      # 4) clasp をインストール（最新の安定版を指定）
      - name: Install clasp (stable)
        run: npm install --global @google/clasp@latest


      # 5) .clasp.json を書き込み（SCRIPT_ID を設定）
      - name: Write .clasp.json
        run: |
          echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json

      # 6) デバッグ用のログ出力（念のためディレクトリ・ファイル構造や環境変数を表示）
      - name: "Debug: List files and verify .clasp.json"
        if: failure()
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la

          echo ""
          echo "--- Contents of .clasp.json ---"
          cat .clasp.json || echo "(not found)"

          echo ""
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"

      # 7) clasp push で Apps Script にデプロイ
      - name: Push to Apps Script
        run: |
          echo "=== Deploying to Apps Script via clasp ==="
          clasp push --force --adc
