name: deploy-gas-webapp
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'         # src 以下のファイル・フォルダに変更があったときのみ
# ここで GITHUB_TOKEN に contents: write を与える
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # persist-credentials: true が既定ですが、念のため明示的に
          persist-credentials: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Install clasp
        run: npm install --global @google/clasp@latest
      - name: Configure clasp auth
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json
      - name: Push to GAS
        run: |
          set -eux
          clasp push --force
      - name: Bump version and push
        if: ${{ success() }}
        run: |
          set -eux
          npm version patch --no-git-tag-version
          NEW_VER=$(node -p "require('./package.json').version")
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json src/Code.gs tests/Code.test.js
          git commit -m "Bump version to v${NEW_VER} [skip ci]"
          git push
          
