name: deploy-gas-webapp
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'         # src 以下のファイル・フォルダに変更があったときのみ

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install --global @google/clasp@latest

      - name: Configure clasp auth
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json

      - name: Push & Update Web App
        id: deploy
        run: |
          set -eux
          clasp push --force
          NEW_VER=$(clasp version "auto-$(date +%Y%m%d%H%M%S)" \
            | grep -oE "[0-9]+" | head -n1)
          [ -n "$NEW_VER" ] || { echo "Failed to retrieve version" >&2; exit 1; }
          clasp update-deployment "${DEPLOYMENT_ID}" \
            --versionNumber "${NEW_VER}" \
            --description "auto-deploy from GitHub Actions"
          echo "webapp_url=https://script.google.com/macros/s/${DEPLOYMENT_ID}/exec?page=login" \
            >> "$GITHUB_OUTPUT"
      - name: Show URL
        run: echo "${{ steps.deploy.outputs.webapp_url }}"

      - name: Bump version and commit
        if: success()
        run: |
          set -eux
          npm version patch --no-git-tag-version
          NEW_VER=$(node -p "require('./package.json').version")
          sed -i "s/^const SQ_VERSION           = 'v[0-9.]*';$/const SQ_VERSION           = 'v${NEW_VER}';/" src/Code.gs
          sed -i "s/expect(getSqVersion()).toBe('v[0-9.]*');/expect(getSqVersion()).toBe('v${NEW_VER}');/" tests/Code.test.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json src/Code.gs tests/Code.test.js
          git commit -m "Bump version to v${NEW_VER} [skip ci]"
          git push
          