name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # 2. Node.js 環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Clasp CLI をインストール
      - name: Install clasp
        run: npm install -g @google/clasp@3.0.6-alpha

      # 4. .clasp.json を作成（Script ID を指定）
      - name: Create .clasp.json
        run: |
          echo "{\"scriptId\":\"${{ secrets.SCRIPT_ID }}\"}" > .clasp.json

      # 5. サービスアカウントキーでログイン（ここが最重要）
      - name: Authenticate with service account
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GCP_CREDENTIALS}" | base64 -d > ./credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json" >> $GITHUB_ENV

      # 6. コードを Google Apps Script にプッシュ
      - name: Push to Google Apps Script
        run: clasp push --force --adc
