name: deploy-gas-webapp
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Install clasp
        run: npm install --global @google/clasp@latest

      - name: Configure clasp auth
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json

      - name: Push & Update Web App
        id: deploy
        run: |
          set -eux

          # 1) コードを強制アップロード
          clasp push --force

          # 2) 新しいバージョンを作成し、番号を抽出
          NEW_VER=$(clasp version "auto-$(date +%Y%m%d%H%M%S)" \
            | grep -oE "[0-9]+" | head -n1)
          if [ -z "$NEW_VER" ]; then
            echo "Failed to retrieve version number" >&2
            exit 1
          fi
          echo "→ Version: $NEW_VER"

          # 3) 既存 Web App (タイプ：webapp) のデプロイをバージョンだけ上書き
          clasp update-deployment "${DEPLOYMENT_ID}" \
            --versionNumber "${NEW_VER}" \
            --description "auto-deploy from GitHub Actions"

          # 4) 固定 URL に ?page=login を付与
          echo "webapp_url=https://script.google.com/macros/s/${DEPLOYMENT_ID}/exec?page=login" \
            >> "$GITHUB_OUTPUT"

      - name: Show URL
        run: echo "${{ steps.deploy.outputs.webapp_url }}"
