name: Deploy GAS Project

on:
  push:
    branches:
      - main

jobs:
  deploy-gas:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    env:
      CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}  # ローカルで取得した ~/.clasprc.json の中身
      GCP_PROJECT: gas-deploy-project

    steps:
      # 1) コードのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Node.js と clasp をインストール
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp (latest)
        run: npm install --global @google/clasp@latest

      # 3) CLASPRC_JSON を ~/.clasprc.json に書き出し → clasp の認証情報を復元
      - name: Restore OAuth credentials for clasp
        run: |
          mkdir -p ~/.config
          echo "${CLASPRC_JSON}" > ~/.clasprc.json

      # ※以下の「Enable Apps Script API」ステップはすでに有効化済みなら不要なので、削除またはコメントアウトします
      # - name: Enable Apps Script API
      #   run: |
      #     gcloud config set project ${GCP_PROJECT}
      #     gcloud services enable script.googleapis.com
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  # サービスアカウントキーを別途用意している場合のみ必要

      # 4) clasp push
      - name: Push to Apps Script
        run: |
          echo "=== Deploying to Apps Script via clasp ==="
          clasp push --force
