name: Deploy GAS Project

on:
  push:
    branches:
      - main

jobs:
  deploy-gas:
    name: Deploy GAS via clasp
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    env:
      GCP_PROJECT: gas-deploy-project

    steps:
      # 1) ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Node.js をセットアップ（clasp は Node.js 上のツールなので必要）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Google への認証
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: false   # ← false にして、認証ファイルを削除しない

      # 4) gcloud CLI のセットアップ（プロジェクト指定など）
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ steps.auth.outputs.project_id }}

      # 5) Apps Script API を有効化（既に有効化済みでも安全に通過）
      - name: Enable Apps Script API
        run: |
          gcloud services enable script.googleapis.com --project=$GCP_PROJECT

      # 5b) Wait until the API is fully enabled before continuing
      - name: Confirm Apps Script API enabled
        run: |
          echo "Waiting for script.googleapis.com to be ENABLED..."
          for i in {1..10}; do
            state=$(gcloud services list --project=$GCP_PROJECT \
              --filter="config.name:script.googleapis.com" \
              --format="value(state)" || true)
            if [ "$state" = "ENABLED" ]; then
              echo "Apps Script API is ENABLED"
              break
            fi
            echo "Current state: $state (retrying)"
            sleep 3
          done
          final_state=$(gcloud services list --project=$GCP_PROJECT \
            --filter="config.name:script.googleapis.com" \
            --format="value(state)")
          if [ "$final_state" != "ENABLED" ]; then
            echo "script.googleapis.com did not become ENABLED in time" >&2
            exit 1
          fi

      # 6) clasp をインストール（最新の安定版を指定）
      - name: Install clasp (stable)
        run: npm install --global @google/clasp@latest

      # 7) clasp で Apps Script にデプロイ
      - name: Push to Apps Script
        run: |
          echo "=== Deploying to Apps Script via clasp ==="
          # プッシュ実行（ADC を利用）
          clasp push --force --adc
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
