name: Build & Deploy GAS

on:
  push:
    branches:
      - main         # main ブランチにプッシュされたときに実行
  workflow_dispatch: # 手動トリガーも可能にする

jobs:
  deploy:
    name: Deploy GAS via clasp
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js をセットアップ (v20.x)
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: clasp をインストール (@google/clasp v3)
        run: npm install --global @google/clasp@3.0.6-alpha

      - name: Secrets の Base64 を復元してファイル保存
        run: |
          # GitHub Secrets に登録したキー名が "GCP_CREDENTIALS" であれば、以下のように復元します
          echo "$GCP_CREDENTIALS" | base64 -d > "$HOME/gcp-sa.json"
          # 環境変数として設定。clasp の ADC 認証で使う
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-sa.json" >> $GITHUB_ENV

      - name: .clasp.json に scriptId を書き込む
        run: |
          # GitHub Secrets に登録したキー名が "SCRIPT_ID" であれば、こうして JSON を生成します
          echo "{\"scriptId\":\"${SCRIPT_ID}\"}" > .clasp.json

      - name: clasp push --force --adc (GAS にデプロイ)
        run: |
          # ADC（Application Default Credentials）モードで GAS プロジェクトを上書きプッシュ
          clasp push --force --adc
